export const CURRENCIES = {
    Indonesia: {
        code: "IDR",
        countryCode: "ID",
        name: "Indonesian Rupiah",
        symbol: "Rp",
    },
    "United States": {
        code: "USD",
        countryCode: "US",
        name: "United States Dollar",
        symbol: "$",
    },
    Japan: {
        code: "JPY",
        countryCode: "JP",
        name: "Japanese Yen",
        symbol: "¥",
    },
    Singapore: {
        code: "SGD",
        countryCode: "SG",
        name: "Singapore Dollar",
        symbol: "S$",
    },
    "Saudi Arabia": {
        code: "SAR",
        countryCode: "SA",
        name: "Saudi Riyal",
        symbol: "﷼",
    },
    "Hong Kong": {
        code: "HKD",
        countryCode: "HK",
        name: "Hong Kong Dollar",
        symbol: "HK$",
    },
    "United Kingdom": {
        code: "GBP",
        countryCode: "GB",
        name: "British Pound Sterling",
        symbol: "£",
    },
    China: {
        code: "CNY",
        countryCode: "CN",
        name: "Chinese Yuan",
        symbol: "¥",
    },
    "New Zealand": {
        code: "NZD",
        countryCode: "NZ",
        name: "New Zealand Dollar",
        symbol: "NZ$",
    },
    Sweden: {
        code: "SEK",
        countryCode: "SE",
        name: "Swedish Krona",
        symbol: "kr",
    },
    "United Arab Emirates": {
        code: "AED",
        countryCode: "AE",
        name: "UAE Dirham",
        symbol: "د.إ",
    },
    Norway: {
        code: "NOK",
        countryCode: "NO",
        name: "Norwegian Krone",
        symbol: "kr",
    },
    Eurozone: {
        code: "EUR",
        countryCode: "EU",
        name: "Euro",
        symbol: "€",
    },
    Switzerland: {
        code: "CHF",
        countryCode: "CH",
        name: "Swiss Franc",
        symbol: "CHF",
    },
    Canada: {
        code: "CAD",
        countryCode: "CA",
        name: "Canadian Dollar",
        symbol: "$",
    },
    Australia: {
        code: "AUD",
        countryCode: "AU",
        name: "Australian Dollar",
        symbol: "A$",
    },
    Taiwan: {
        code: "TWD",
        countryCode: "TW",
        name: "New Taiwan Dollar",
        symbol: "NT$",
    },
    ALL: {
        code: "ALL",
        countryCode: "ALL",
        name: "ALL",
        symbol: "ALL",
    },
} as const;
